---
ID: "376da354-62fb-4066-ade3-439419eae7a8"
Parent: "877091a7-131e-40d2-bdc6-5534284c5d03"
Template: "9f6e14e6-c593-410b-a57e-21f6b5a413ad"
Path: /sitecore/system/Settings/Buckets/Item Buckets Settings
DB: master
SharedFields:
- ID: "5a81d794-7364-4cc5-8aa9-a921d5dda4af"
  Hint: Opening Search Results
  Value: New Tab
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111026T193900Z
